config/routes.rb
Ticketee::Application.routes.draw do
	root to: 'projects#index'
	resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
	end
	
	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)

		if @project.save
			redirect_to @project, notice: "Project has been created."
		else
			flash[:alert] = "Project has not been created."
			render action: "new"
		end
	end

	def show
		@project = Project.find(params[:id])
	end

	private

		def project_params
			params.require(:project).permit(:name, :description)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "Ticketee").join(" - ")
			end
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		<% if content_for?(:title) %>
			<%= yield(:title) %>
		<% else %>
			Ticketee
		<% end %>
	</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |k,v| %>
		<div class="flash" id="<%= k %>">
			<%= v %>
		</div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<h1>Tutaj założysz nowy projekcik</h1>
<p>Psia parówo</p>

<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= form_for(@project) do |f| %>
	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %><br />
		<%= f.text_field :description %>
	</p>
	<%= f.submit %>
<% end %>

<% if @project.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@project.errors.count, "error") %>
			prohibited this project from being saved:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>
<p>
	<%= @project.description %>
</p>